stages:
  featurize:
    cmd: python featurize.py dataset features/preprocessed_ds.csv
    deps:
    - dataset
    - featurize.py
    params:
    - featurize.max_sample
    - featurize.min_df
    - featurize.pca_ratio
    outs:
    - features/preprocessed_ds.csv
  train:
    cmd: python train.py features models/svc.joblib
    deps:
    - features
    - train.py
    params:
    - train.svc_kernel
    - train.test_size
    outs:
    - models/svc.joblib
  evaluate:
    cmd: python evaluate.py features/preprocessed_ds.csv models/svc.joblib
    deps:
    - evaluate.py
    - features/preprocessed_ds.csv
    - models/svc.joblib
    params:
    - evaluate.test_size

metrics:
- eval/metrics.json
plots:
- eval/plots/sklearn/cm/test.json:
    template: confusion
    x: actual
    y: predicted
    title: Confusion Matrix
    x_label: True Label
    y_label: Predicted Label
