stages:
  featurize:
    cmd: python mlops_dvc/featurize.py
    deps:
    - dataset/train.csv
    - mlops_dvc/featurize.py
    params:
    - featurize.max_samples
    - featurize.min_df
    - featurize.pca_ratio
    outs:
    - dataset/preprocessed_ds.csv
  train:
    cmd: python mlops_dvc/train.py dataset/preprocessed_ds.csv svc.joblib
    deps:
    - dataset/preprocessed_ds.csv
    - mlops_dvc/train.py
    params:
    - train.kernel
    - train.test_size
    outs:
    - svc.joblib
  evaluate:
    cmd: python mlops_dvc/evaluate.py dataset/preprocessed_ds.csv svc.joblib
    deps:
    - dataset/preprocessed_ds.csv
    - mlops_dvc/evaluate.py
    - svc.joblib
    params:
    - evaluate.test_size
